#!/bin/bash
DEPENDENCIES="vim runit runit-systemd"
BASHRC_PATH="/home/pi/.bashrc"
BASH_MCLIENT_PATH="/home/pi/.bash_mclient"

# exit on failure
set -e

# ensure script is run as root
if [ "$(id -u)" != "0" ]; then
  echo "permission denied (try sudo)"
  exit 1
fi

# install each package if not exists
for PACKAGE in $DEPENDENCIES; do
    if ! dpkg-query -l "$PACKAGE" > /dev/null; then
        apt-get -y install "$PACKAGE"
    else
        echo "$PACKAGE is already installed"
    fi
done

# create directories and files used by runit
mkdir -p /etc/sv/mclient
mkdir -p /var/log/mclient
touch /var/log/mclient/current

# copy runit config to device
cp -vr /home/pi/mclient/home/pi /home
cp -vr /home/pi/mclient/etc/sv/mclient /etc/sv

# initialize runit by symlinking /etc/service (if not exists)
if [ ! -d /etc/service/mclient ]; then
    ln -s /etc/sv/mclient /etc/service/mclient
fi

# source .bash_mclient from .bashrc if not already done
if ! cat $BASHRC_PATH | grep "source /home/pi/.bash_mclient" >> /dev/null; then
    echo "source $BASH_MCLIENT_PATH" >> $BASHRC_PATH
fi

echo "install completed successfully"
echo "please reboot to initialize mclient service"
